spring:
  application:
    name: msClientes

server:
    # A porta '0' indica que a aplicação deve gerar portas randomicas
    port: 0

eureka:
  client:
    service-url:
      defaultZone: http://cursoms-eureka-user:cseeskrero--sumuaur@localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  file:
    name: ./logs/log-file.log